# Generated by Django 2.1.10 on 2020-12-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('user', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名')),
                ('user_email', models.CharField(default=True, max_length=64, verbose_name='用户邮箱')),
                ('user_mobile', models.IntegerField(unique=True, verbose_name='用户手机号')),
            ],
        ),
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(verbose_name='账号')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='余额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='交易金额')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('status', models.IntegerField(choices=[(0, '交易中'), (1, '交易成功'), (2, '交易失败')], default=1, verbose_name='交易状态')),
                ('associated_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_account', verbose_name='关联账户')),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='关联用户')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='u_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_account'),
        ),
    ]
